#ifndef HTML_TEMPLATE_H
#define HTML_TEMPLATE_H

const char* HTML_TEMPLATE_PART_1 = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>CodeLens — Review Report</title>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&family=JetBrains+Mono:wght@400;600&display=swap\" rel=\"stylesheet\">\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #08090e;\n"
"            --card-bg: rgba(20, 21, 38, 0.6);\n"
"            --border: rgba(255, 255, 255, 0.08);\n"
"            --text-main: #f1f1f8;\n"
"            --text-muted: #959bb4;\n"
"            --primary: #8b5cf6;\n"
"            --primary-glow: rgba(139, 92, 246, 0.25);\n"
"            --secondary: #3b82f6;\n"
"            --secondary-glow: rgba(59, 130, 246, 0.25);\n"
"            --danger: #ef4444;\n"
"            --danger-glow: rgba(239, 68, 68, 0.2);\n"
"            --success: #10b981;\n"
"            --success-glow: rgba(16, 185, 129, 0.2);\n"
"            --warning: #f59e0b;\n"
"        }\n"
"        * {\n"
"            box-sizing: border-box;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"        }\n"
"        body {\n"
"            background-color: var(--bg-color);\n"
"            color: var(--text-main);\n"
"            font-family: 'Outfit', sans-serif;\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            background-image: \n"
"                radial-gradient(circle at 5% 5%, rgba(139, 92, 246, 0.06) 0%, transparent 35%),\n"
"                radial-gradient(circle at 95% 95%, rgba(59, 130, 246, 0.06) 0%, transparent 35%);\n"
"        }\n"
"        header {\n"
"            background: rgba(12, 13, 20, 0.8);\n"
"            backdrop-filter: blur(12px);\n"
"            border-bottom: 1px solid var(--border);\n"
"            padding: 1rem 2rem;\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            position: sticky;\n"
"            top: 0;\n"
"            z-index: 100;\n"
"        }\n"
"        .logo {\n"
"            font-size: 1.35rem;\n"
"            font-weight: 700;\n"
"            background: linear-gradient(135deg, #c084fc, #6366f1);\n"
"            -webkit-background-clip: text;\n"
"            -webkit-text-fill-color: transparent;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 0.5rem;\n"
"        }\n"
"        .logo-tag {\n"
"            background: rgba(139, 92, 246, 0.12);\n"
"            color: #c084fc;\n"
"            font-size: 0.7rem;\n"
"            padding: 0.15rem 0.45rem;\n"
"            border-radius: 5px;\n"
"            border: 1px solid rgba(139, 92, 246, 0.25);\n"
"        }\n"
"        .container {\n"
"            max-width: 1280px;\n"
"            margin: 1.5rem auto;\n"
"            padding: 0 1.5rem;\n"
"            width: 100%;\n"
"            flex-grow: 1;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 1.5rem;\n"
"        }\n"
"        /* Top Stats row */\n"
"        .stats-row {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
"            gap: 1rem;\n"
"        }\n"
"        .stat-card {\n"
"            background: var(--card-bg);\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 12px;\n"
"            padding: 1.25rem;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 0.25rem;\n"
"        }\n"
"        .stat-label {\n"
"            font-size: 0.8rem;\n"
"            color: var(--text-muted);\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 0.05em;\n"
"        }\n"
"        .stat-value {\n"
"            font-size: 1.85rem;\n"
"            font-weight: 700;\n"
"        }\n"
"        .stat-value.primary { color: #c084fc; text-shadow: 0 0 8px rgba(192, 132, 252, 0.2); }\n"
"        .stat-value.danger { color: var(--danger); text-shadow: 0 0 8px var(--danger-glow); }\n"
"        .stat-value.success { color: var(--success); text-shadow: 0 0 8px var(--success-glow); }\n"
"        \n"
"        /* Main panels layout */\n"
"        .main-layout {\n"
"            display: grid;\n"
"            grid-template-columns: 1fr;\n"
"            gap: 1.5rem;\n"
"        }\n"
"        @media (min-width: 992px) {\n"
"            .main-layout { grid-template-columns: 2fr 1fr; }\n"
"        }\n"
"        \n"
"        .panel {\n"
"            background: var(--card-bg);\n"
"            backdrop-filter: blur(12px);\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 16px;\n"
"            padding: 1.5rem;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 1.25rem;\n"
"        }\n"
"        .panel-title {\n"
"            font-size: 1.1rem;\n"
"            font-weight: 600;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 0.5rem;\n"
"            border-bottom: 1px solid var(--border);\n"
"            padding-bottom: 0.75rem;\n"
"            color: var(--text-main);\n"
"        }\n"
"        \n"
"        /* File and Violation Display */\n"
"        .file-section {\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 10px;\n"
"            background: rgba(255, 255, 255, 0.01);\n"
"            overflow: hidden;\n"
"            margin-bottom: 1rem;\n"
"        }\n"
"        .file-header {\n"
"            background: rgba(255, 255, 255, 0.03);\n"
"            padding: 0.75rem 1rem;\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            font-weight: 600;\n"
"            font-size: 0.92rem;\n"
"            border-bottom: 1px solid var(--border);\n"
"        }\n"
"        .file-path {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 0.4rem;\n"
"        }\n"
"        .file-path::before { content: \"📄\"; }\n"
"        .file-badge {\n"
"            font-size: 0.75rem;\n"
"            padding: 0.15rem 0.5rem;\n"
"            border-radius: 8px;\n"
"            font-weight: 600;\n"
"        }\n"
"        .file-badge.danger {\n"
"            background: rgba(239, 68, 68, 0.15);\n"
"            color: #fca5a5;\n"
"            border: 1px solid rgba(239, 68, 68, 0.25);\n"
"        }\n"
"        .file-badge.success {\n"
"            background: rgba(16, 185, 129, 0.15);\n"
"            color: #a7f3d0;\n"
"            border: 1px solid rgba(16, 185, 129, 0.25);\n"
"        }\n"
"        .violation-list {\n"
"            padding: 0.75rem;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 0.75rem;\n"
"        }\n"
"        .violation-item {\n"
"            background: rgba(0, 0, 0, 0.18);\n"
"            border: 1px solid rgba(255, 255, 255, 0.03);\n"
"            border-left: 3px solid var(--danger);\n"
"            border-radius: 6px;\n"
"            padding: 0.75rem;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            gap: 0.4rem;\n"
"        }\n"
"        .v-meta {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            font-size: 0.8rem;\n"
"            color: var(--text-muted);\n"
"            font-weight: 600;\n"
"        }\n"
"        .v-type {\n"
"            color: #fda4af;\n"
"            background: rgba(239, 68, 68, 0.1);\n"
"            padding: 0.1rem 0.4rem;\n"
"            border-radius: 4px;\n"
"            border: 1px solid rgba(239, 68, 68, 0.15);\n"
"        }\n"
"        .v-code {\n"
"            font-family: 'JetBrains Mono', monospace;\n"
"            font-size: 0.82rem;\n"
"            color: #f3f4f6;\n"
"            background: #07070d;\n"
"            padding: 0.5rem;\n"
"            border-radius: 4px;\n"
"            overflow-x: auto;\n"
"            white-space: pre;\n"
"            border: 1px solid rgba(255, 255, 255, 0.02);\n"
"        }\n"
"        \n"
"        /* Selector & Shift Matrix */\n"
"        select {\n"
"            width: 100%;\n"
"            padding: 0.65rem 0.85rem;\n"
"            background: #0f101b;\n"
"            color: var(--text-main);\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 8px;\n"
"            font-family: 'Outfit', sans-serif;\n"
"            font-size: 0.9rem;\n"
"            outline: none;\n"
"            cursor: pointer;\n"
"        }\n"
"        select:focus { border-color: var(--primary); }\n"
"        \n"
"        .shift-grid {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(auto-fill, minmax(65px, 1fr));\n"
"            gap: 0.4rem;\n"
"            margin-top: 0.5rem;\n"
"        }\n"
"        .shift-card {\n"
"            background: rgba(255, 255, 255, 0.015);\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 6px;\n"
"            padding: 0.4rem;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            gap: 0.1rem;\n"
"        }\n"
"        .shift-char {\n"
"            font-family: 'JetBrains Mono', monospace;\n"
"            font-weight: 600;\n"
"            color: #a78bfa;\n"
"            font-size: 0.9rem;\n"
"        }\n"
"        .shift-val {\n"
"            font-size: 0.75rem;\n"
"            color: var(--text-muted);\n"
"        }\n"
"        \n"
"        /* General widgets */\n"
"        .sim-item {\n"
"            background: rgba(255, 255, 255, 0.01);\n"
"            border: 1px solid var(--border);\n"
"            border-radius: 8px;\n"
"            padding: 0.75rem 1rem;\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            font-size: 0.85rem;\n"
"            font-weight: 600;\n"
"        }\n"
"        .sim-files { display: flex; align-items: center; gap: 0.4rem; }\n"
"        .sim-val { color: var(--warning); font-weight: 700; }\n"
"        .sim-val.safe { color: var(--success); }\n"
"        \n"
"        footer {\n"
"            text-align: center;\n"
"            padding: 1.5rem;\n"
"            color: var(--text-muted);\n"
"            font-size: 0.8rem;\n"
"            border-top: 1px solid var(--border);\n"
"            margin-top: auto;\n"
"            background: rgba(10, 11, 18, 0.8);\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <header>\n"
"        <div class=\"logo\">\n"
"            CodeLens <span class=\"logo-tag\">Review Dashboard</span>\n"
"        </div>\n"
"        <div style=\"font-size:0.8rem; color:var(--text-muted);\" id=\"header-time\"></div>\n"
"    </header>\n"
"    \n"
"    <div class=\"container\">\n"
"        <!-- Executive stats -->\n"
"        <div class=\"stats-row\">\n"
"            <div class=\"stat-card\">\n"
"                <span class=\"stat-label\">Scanned Files</span>\n"
"                <span class=\"stat-value primary\" id=\"metric-files\">0</span>\n"
"            </div>\n"
"            <div class=\"stat-card\">\n"
"                <span class=\"stat-label\">Total Violations</span>\n"
"                <span class=\"stat-value danger\" id=\"metric-violations\">0</span>\n"
"            </div>\n"
"            <div class=\"stat-card\">\n"
"                <span class=\"stat-label\">Horspool Matches</span>\n"
"                <span class=\"stat-value success\" id=\"metric-matches\">0</span>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- Main Dashboard panels layout -->\n"
"        <div class=\"main-layout\">\n"
"            <!-- Left panel: Code Scan Violations -->\n"
"            <div class=\"panel\">\n"
"                <h3 class=\"panel-title\">🔍 Code Review Scan Report</h3>\n"
"                <div id=\"report-files-container\"></div>\n"
"            </div>\n"
"            \n"
"            <!-- Right panel: Algorithms & Shift Tables -->\n"
"            <div style=\"display:flex; flex-direction:column; gap:1.5rem;\">\n"
"                <div class=\"panel\">\n"
"                    <h3 class=\"panel-title\">📋 Horspool Shift Table</h3>\n"
"                    <div>\n"
"                        <select id=\"shift-selector\" onchange=\"updateShiftDisplay()\">\n"
"                            <option value=\"\">Select a pattern...</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"shift-grid\" id=\"shift-table-grid\">\n"
"                        <div style=\"grid-column:1/-1; text-align:center; padding:1.5rem 0; color:var(--text-muted); font-size:0.85rem;\">\n"
"                            Select a pattern to view shifts.\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                \n"
"                <div class=\"panel\">\n"
"                    <h3 class=\"panel-title\">👥 File Copy Duplications</h3>\n"
"                    <div style=\"display:flex; flex-direction:column; gap:0.6rem;\" id=\"similarity-container\">\n"
"                        <div style=\"text-align:center; padding:1rem 0; color:var(--text-muted); font-size:0.85rem;\">\n"
"                            No copy data.\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <footer>\n"
"        CodeLens Interactive Scan Dashboard • Generated via Boyer-Moore-Horspool Engine\n"
"    </footer>\n"
"    \n"
"    <pre id=\"raw-report-data\" style=\"display:none;\">\n";

const char* HTML_TEMPLATE_PART_2 = 
"    </pre>\n"
"    \n"
"    <script>\n"
"        let files = [];\n"
"        let fileViolations = {};\n"
"        let benchmark = { horspoolTime: 0.0, naiveTime: 0.0, matches: 0 };\n"
"        let similarities = [];\n"
"        let shiftTables = {};\n"
"        \n"
"        function parseReport() {\n"
"            const raw = document.getElementById('raw-report-data').textContent.trim();\n"
"            \n"
"            // 1. Generation date\n"
"            const dateMatch = raw.match(/Generated\\s*:\\s*(.*)/);\n"
"            if (dateMatch) {\n"
"                document.getElementById('header-time').textContent = \"Generated: \" + dateMatch[1].trim();\n"
"            }\n"
"            \n"
"            // 2. Scan list\n"
"            const filesMatch = raw.match(/Files:\\n([\\s\\S]*?)\\n\\n/);\n"
"            if (filesMatch) {\n"
"                const lines = filesMatch[1].trim().split('\\n');\n"
"                lines.forEach(line => {\n"
"                    const m = line.match(/\\[\\d+\\]\\s*(.*)/);\n"
"                    if (m) files.push(m[1].trim());\n"
"                });\n"
"            }\n"
"            \n"
"            // 3. Scan violations blocks\n"
"            const fileBlocks = raw.split(/={40}\\nFILE:\\s*/);\n"
"            fileBlocks.slice(1).forEach(block => {\n"
"                const lines = block.split('\\n');\n"
"                const filename = lines[0].trim().replace(/={40}/, '').trim();\n"
"                \n"
"                fileViolations[filename] = [];\n"
"                \n"
"                const violationsText = block.split(/\\-{40}/);\n"
"                violationsText.forEach(vText => {\n"
"                    const typeMatch = vText.match(/Violation Type\\s*:\\s*(.*)/);\n"
"                    const lineMatch = vText.match(/Line Number\\s*:\\s*(\\d+)/);\n"
"                    const codeMatch = vText.match(/Matched Code\\s*:\\s*(.*)/);\n"
"                    \n"
"                    if (typeMatch && lineMatch) {\n"
"                        fileViolations[filename].push({\n"
"                            type: typeMatch[1].trim(),\n"
"                            line: parseInt(lineMatch[1].trim()),\n"
"                            code: codeMatch ? codeMatch[1].trim() : \"\"\n"
"                        });\n"
"                    }\n"
"                });\n"
"            });\n"
"            \n"
"            // Ensure all files are in list\n"
"            files.forEach(f => {\n"
"                if (!fileViolations[f]) fileViolations[f] = [];\n"
"            });\n"
"            \n"
"            // 4. Benchmark\n"
"            const benchSection = raw.match(/={8} PERFORMANCE BENCHMARK ={8}\\n([\\s\\S]*?)(?=={8})/);\n"
"            if (benchSection) {\n"
"                const bText = benchSection[1];\n"
"                const horspoolLine = bText.match(/Horspool\\s+(\\d+)\\s+([\\d.]+)/);\n"
"                if (horspoolLine) {\n"
"                    benchmark.matches = parseInt(horspoolLine[1]);\n"
"                }\n"
"            }\n"
"            \n"
"            // 5. Similarity\n"
"            const simSection = raw.match(/={8} SIMILARITY SCORES \\(test_files\\) ={8}\\n([\\s\\S]*?)(?=={8})/);\n"
"            if (simSection) {\n"
"                const lines = simSection[1].trim().split('\\n');\n"
"                lines.forEach(line => {\n"
"                    const m = line.trim().match(/([\\d.]+)%\\s+(.*?)\\s+<->\\s+(.*)/);\n"
"                    if (m) {\n"
"                        similarities.push({\n"
"                            score: parseFloat(m[1]),\n"
"                            file1: m[2].trim(),\n"
"                            file2: m[3].trim()\n"
"                        });\n"
"                    }\n"
"                });\n"
"            }\n"
"            \n"
"            // Reconstruct BM-Horspool shift tables locally in Javascript\n"
"            const patterns = [\"eval(\", \"goto\", \"password\", \"TODO\", \"strcpy\"];\n"
"            patterns.forEach(pat => {\n"
"                shiftTables[pat] = {};\n"
"                let m = pat.length;\n"
"                for (let i = 0; i < 256; i++) {\n"
"                    shiftTables[pat][String.fromCharCode(i)] = m;\n"
"                }\n"
"                for (let i = 0; i < m - 1; i++) {\n"
"                    shiftTables[pat][pat[i]] = m - 1 - i;\n"
"                }\n"
"            });\n"
"        }\n"
"        \n"
"        function render() {\n"
"            // Render stats\n"
"            document.getElementById('metric-files').textContent = files.length;\n"
"            let vTotal = 0;\n"
"            Object.keys(fileViolations).forEach(k => vTotal += fileViolations[k].length);\n"
"            document.getElementById('metric-violations').textContent = vTotal;\n"
"            document.getElementById('metric-matches').textContent = benchmark.matches || 0;\n"
"            \n"
"            // Render reports list\n"
"            const repContainer = document.getElementById('report-files-container');\n"
"            repContainer.innerHTML = \"\";\n"
"            \n"
"            files.forEach(f => {\n"
"                const fileSec = document.createElement('div');\n"
"                fileSec.className = \"file-section\";\n"
"                \n"
"                const basename = f.split(/\\\\|\\//).pop();\n"
"                const violations = fileViolations[f] || [];\n"
"                const count = violations.length;\n"
"                \n"
"                const badgeClass = count > 0 ? \"danger\" : \"success\";\n"
"                const badgeText = count > 0 ? count + \" violations\" : \"Clean\";\n"
"                \n"
"                let listHtml = \"\";\n"
"                if (count === 0) {\n"
"                    listHtml = `<div style=\"padding:1rem; text-align:center; color:var(--success); font-size:0.85rem; font-weight:600;\">✨ File is clean! No matches found.</div>`;\n"
"                } else {\n"
"                    listHtml = `<div class=\"violation-list\">`;\n"
"                    violations.forEach(v => {\n"
"                        listHtml += `\n"
"                            <div class=\"violation-item\">\n"
"                                <div class=\"v-meta\">\n"
"                                    <span class=\"v-type\">Pattern: ${v.type}</span>\n"
"                                    <span>Line ${v.line}</span>\n"
"                                </div>\n"
"                                <div class=\"v-code\">${escapeHtml(v.code)}</div>\n"
"                            </div>\n"
"                        `;\n"
"                    });\n"
"                    listHtml += `</div>`;\n"
"                }\n"
"                \n"
"                fileSec.innerHTML = `\n"
"                    <div class=\"file-header\">\n"
"                        <span class=\"file-path\">${basename}</span>\n"
"                        <span class=\"file-badge ${badgeClass}\">${badgeText}</span>\n"
"                    </div>\n"
"                    ${listHtml}\n"
"                `;\n"
"                repContainer.appendChild(fileSec);\n"
"            });\n"
"            \n"
"            // Populate Shift Table dropdown selector\n"
"            const selector = document.getElementById('shift-selector');\n"
"            selector.innerHTML = `<option value=\"\">Select a pattern...</option>`;\n"
"            Object.keys(shiftTables).forEach(pat => {\n"
"                const opt = document.createElement('option');\n"
"                opt.value = pat;\n"
"                opt.textContent = `\"${pat}\"`;\n"
"                selector.appendChild(opt);\n"
"            });\n"
"            \n"
"            // Render Copy Paste duplications list\n"
"            const simContainer = document.getElementById('similarity-container');\n"
"            simContainer.innerHTML = \"\";\n"
"            if (similarities.length === 0) {\n"
"                simContainer.innerHTML = `<div style=\"text-align:center; color:var(--text-muted); font-size:0.85rem;\">No comparisons.</div>`;\n"
"            } else {\n"
"                similarities.forEach(s => {\n"
"                    const item = document.createElement('div');\n"
"                    item.className = \"sim-item\";\n"
"                    const isHigh = s.score >= 50.0;\n"
"                    item.innerHTML = `\n"
"                        <div class=\"sim-files\">\n"
"                            <span>📄 ${s.file1.split(/\\\\|\\//).pop()}</span>\n"
"                            <span style=\"color:var(--text-muted);\">↔</span>\n"
"                            <span>📄 ${s.file2.split(/\\\\|\\//).pop()}</span>\n"
"                        </div>\n"
"                        <span class=\"sim-val ${!isHigh ? 'safe' : ''}\">${s.score}%</span>\n"
"                    `;\n"
"                    simContainer.appendChild(item);\n"
"                });\n"
"            }\n"
"        }\n"
"        \n"
"        function updateShiftDisplay() {\n"
"            const pat = document.getElementById('shift-selector').value;\n"
"            const grid = document.getElementById('shift-table-grid');\n"
"            grid.innerHTML = \"\";\n"
"            \n"
"            if (!pat) {\n"
"                grid.innerHTML = `\n"
"                    <div style=\"grid-column:1/-1; text-align:center; padding:1.5rem 0; color:var(--text-muted); font-size:0.85rem;\">\n"
"                        Select a pattern to view shifts.\n"
"                    </div>\n"
"                `;\n"
"                return;\n"
"            }\n"
"            \n"
"            const shifts = shiftTables[pat];\n"
"            let foundCount = 0;\n"
"            for (let i = 32; i < 127; i++) {\n"
"                const char = String.fromCharCode(i);\n"
"                const shift = shifts[char];\n"
"                if (shift !== pat.length) {\n"
"                    foundCount++;\n"
"                    const card = document.createElement('div');\n"
"                    card.className = \"shift-card\";\n"
"                    card.innerHTML = `\n"
"                        <span class=\"shift-char\">'${char}'</span>\n"
"                        <span class=\"shift-val\">shift: ${shift}</span>\n"
"                    `;\n"
"                    grid.appendChild(card);\n"
"                }\n"
"            }\n"
"            \n"
"            if (foundCount === 0) {\n"
"                grid.innerHTML = `\n"
"                    <div style=\"grid-column:1/-1; text-align:center; padding:1.5rem 0; color:var(--text-muted); font-size:0.85rem;\">\n"
"                        All characters default to shift size: ${pat.length}\n"
"                    </div>\n"
"                `;\n"
"            }\n"
"        }\n"
"        \n"
"        function escapeHtml(text) {\n"
"            return text\n"
"                .replace(/&/g, \"&amp;\")\n"
"                .replace(/</g, \"&lt;\")\n"
"                .replace(/>/g, \"&gt;\");\n"
"        }\n"
"        \n"
"        window.onload = function() {\n"
"            parseReport();\n"
"            render();\n"
"        };\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif
